### ISSUE TITLE
How to pass arguments to the go code?

### ISSUE THREAD

**Issue by n-is** [dkfbasel/hot-reload#8]
I tried passing arguments through ARGUMENTS in environment, but it's not working. How can I pass arguments to my programs?

Thanks,
Nischal Nepal

**Comment by tikiatua** [comment]
Hi @n-is 

Thank you for your message. Could you please try using ARGS as environment variable. Seems like this was changed (in the file config.go) but not adapted in the readme.

**Comment by tikiatua** [comment]
I just updated the readme to also include info on go modules caching.

**Comment by wandercn** [comment]
hotbuild.ffactory.org you can try it now.

**Comment by n-is** [comment]
Thanks @wandercn. Seems like a great project. :+1: 

Will definitely use in my next golang project. :smile:
